# https://taskfile.dev

version: "3"

silent: true

tasks:
  default:
    deps:
      - test

  test:
    cmds:
      - gotest -cover -race ./...

  build:
    deps:
      - tidy
    cmds:
      - go build -o ./bin/w17 .

  tidy:
    cmds:
      - go mod tidy

  run:
    deps:
      - build
    cmds:
      - bin/w17
    silent: true

  commit:
    cmds:
      - git add .
      - git commit

  push:
    deps:
      - commit
      - build
      - test
    cmds:
      - git push
